name: vinyla
description: Application for exchange  com.ua.vinyla

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # DI
  injectable: ^1.5.3
  get_it: ^7.2.0

  # Services
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.2.0
  firebase_core: ^2.4.0

  # Localization
  intl: ^0.17.0

  # UI
  adaptive_navigation: ^0.0.7
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.2
  gravatar_utils: ^1.0.0

  # Navigation
  go_router: ^5.1.5

  # State manager
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  # Generators
  freezed_annotation: ^2.2.0
  freezed: ^2.3.2
  build_runner: ^2.3.2
  json_annotation: ^4.7.0

  # Helpers
  equatable: ^2.0.5
  meta: ^1.8.0

flutter:
  uses-material-design: true
  generate: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  injectable_generator: ^1.5.5
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.1
